apiVersion: v1
kind: Service
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
    sha: '{{{M3_SHA}}}'
spec:
  selector:
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  ports:
    - protocol: TCP
      name: web-frontend
      port: 80
      targetPort: {{{M3_PORT_FRONTEND}}}
    - protocol: TCP
      name: web-backend
      port: 81
      targetPort: {{{M3_PORT_BACKEND}}}
