FROM strapi/base
ARG STRAPI_ADMIN_PATH
ENV STRAPI_ADMIN_PATH=$STRAPI_ADMIN_PAT
ENV NODE_ENV production
WORKDIR /m3ntorshipcom-cms
COPY ./backend/package.json ./
COPY ./backend/yarn.lock ./

COPY ./backend/api ./api
COPY ./backend/components ./components
COPY ./backend/config ./config
COPY ./backend/extensions ./extensions
COPY ./backend/public ./public
COPY ./backend/favicon.ico ./favicon.ico

RUN yarn install
RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]