apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
spec:
  replicas: {{{M3_REPLICAS}}}
  selector:
    matchLabels:
      application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  template:
    metadata:
      labels:
        project: '{{{M3_PROJECT}}}'
        environment: '{{{M3_ENVIRONMENT}}}'
        componenet: '{{{M3_COMPONENET}}}'
        application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    spec:
      containers:
        - name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
          image: '{{{M3_IMAGE}}}:{{{M3_VERSION}}}'
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: DATABASE_HOST
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: DATABASE_PASSWORD
            - name: STRAPI_ADMIN_PATH
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: STRAPI_ADMIN_PATH
            - name: MINIO_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: MINIO_PUBLIC_KEY
            - name: MINIO_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: MINIO_PRIVATE_KEY
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: MINIO_URL
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                  key: MINIO_BUCKET
          ports:
            - name: web
              containerPort: {{{M3_PORT}}}
              protocol: TCP
