apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
    sha: '{{{M3_SHA}}}'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  rules:
    - host: 'm3ntorship.net'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 80
    - host: 'm3ntorship.com'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 80
    - host: 'm3ntorship.tech'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 80
    - host: 'be.m3ntorship.com'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 81
    - host: 'be.m3ntorship.net'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 81
    - host: 'be.m3ntorship.tech'
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
                port:
                  number: 81